# Site settings
title: DCU Science Carnival
email: domhnall@sciencecarnival.net
description: "Science and Entertainment collide at the Science Carnival."
baseurl: "/sciencecarnival"
url: "https://domhnallohanlon.github.io"
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/stemcarnival
  - title: facebook
    url: http://fb.com/stemcarnival
  

# Postal address (add as many lines as necessary)
address:
  - line: Dublin City University
  - line: Dublin 9

# Build settings
markdown: kramdown
permalink: pretty
